### PR TITLE
add test for lsat fixture and change challenge parsing

### LINKED ISSUE #4: Challenge Parsing fails with Base64 padding
Most Base64 encoders use `=` as byte padding. However,[ parseChallengePart](https://github.com/Tierion/lsat-js/blob/master/src/lsat.ts#L23) cannot process anymore than a single equal sign in an invoice or macaroon challenge part, which causes assert failures in cases where a challenger uses a Base64 encoder that pads. 

Replication: Use `LSAT macaroon="AgESMy4xMzYuMTc4LjE1OjM0MjM4AkIAAD2b0rX78LATiVo8bKgHuurefeF5OeX2H5ZuacBIK3+RAR1PKU1oZpfCZFib4zdDoj0pOpgPmhtuzNllU+y//D0AAAYgcWFs9FIteCzpCcEPSwmXKBpcx97hyL5Yt99cbLjRHzU=", invoice="lntb20n1psza5dwpp58kda9d0m7zcp8z2683k2spa6at08mcte88jlv8ukde5uqjpt07gsdzjfp85gnpqd9h8vmmfvdjjqurp09kk2mn5ypn8ymmdyppksctfdecx76twwssyxmmjv5sxcmny8gcnqvps8ycqzpgsp5m7xru8dlhrhmwjp8gynsj2l9mwan2jk52ah5xucrn9kc3p0pj5ns9qy9qsq7jjxypyyc7hvvs8srh6c3lvcp5l5wka94htnfxak99hd5qrx69sya9sj4zm3w5lncw0tksf944q73tduhlhs5apd63m9dte9dhva5dgqaceunx"` on the LSAT playground or in a simple lsat-js script. 

The solution (I think) would be to separate on the comma / whitespace first, then ensure that the first string split is `macaroon` or `invoice`.

It's also possible that my macaroon encoding is not supposed to require any padding, and that my LSAT implementation is wrong. But given that I'm adapting code from the Aperature project, I think this might be less likely.

### PR DESCRIPTION
**Pull request by bucko13**
Partly resolves #4. The other part seems related to the macaroon library being used. It either has a bug or has deliberately forked from the macaroon standard and will need to be replaced. I'm hoping for the former.

In the meantime, this fix still addresses the first error reported. 

The issue was reported [here](https://github.com/nitram509/macaroons.js/issues/51)

### CODE REVIEW

**Comment by bucko13** [comment]
This adds a test for the macaroon from another library and since that's not working right now, that one test will fail.

**Comment by jacohend** [comment]
I see these travis failures:
```
tests/lsat.spec.ts(9,1): error TS6133: 'importMacaroon' is declared but its value is never read.
tests/lsat.spec.ts(9,32): error TS2307: Cannot find module 'macaroon' or its corresponding type declarations.
```

**Comment by bucko13** [comment]
Ah thanks, forgot some cleanup. Unfortunately the tests will still fail since I added a test for the golang macaroon and that's not supported yet in the current macaroon lib. Debating whether or not to just put this fix in with the broken build and then either separately wait to upgrade the macaroon dep or go through the laborious process of ripping out the existing macaroon library...

**Comment by bucko13** [comment]
closing in favor of #8

**Pull request closed without merging**
